### ISSUE TITLE
Issue with netCDF during build 

### ISSUE THREAD

**Issue by SergeDmi** [RangamaniLabUCSD/Mem3DG#52]
When trying to build Mem3DG (with cmake directly or during pip install), a bunch of errors with netcfd appear : 
`
/home/dmitrief/code/Mem3DG/include/mem3dg/solver/mutable_trajfile.h: In destructor ‘mem3dg::solver::MutableTrajFile::~MutableTrajFile()’:
/home/dmitrief/code/Mem3DG/include/mem3dg/solver/mutable_trajfile.h:149:11: error: ‘using NcFile = class netCDF::NcFile’ {aka ‘class netCDF::NcFile’} has no member named ‘close’
       fd->close();
           ^~~~~
/home/dmitrief/code/Mem3DG/include/mem3dg/solver/mutable_trajfile.h: In member function ‘void mem3dg::solver::MutableTrajFile::sync()’:
/home/dmitrief/code/Mem3DG/include/mem3dg/solver/mutable_trajfile.h:228:21: error: ‘using NcFile = class netCDF::NcFile’ {aka ‘class netCDF::NcFile’} has no member named ‘sync’
   void sync() { fd->sync(); }
                     ^~~~
/home/dmitrief/code/Mem3DG/include/mem3dg/solver/mutable_trajfile.h: In member function ‘void mem3dg::solver::MutableTrajFile::close()’:
/home/dmitrief/code/Mem3DG/include/mem3dg/solver/mutable_trajfile.h:238:9: error: ‘using NcFile = class netCDF::NcFile’ {aka ‘class netCDF::NcFile’} has no member named ‘sync’
     fd->sync();
         ^~~~
`
NetCDF-cxx4 (v4.2.1) was installed from conda (conda install -c conda-forge netcdf-cxx4)

**Comment by ctlee** [comment]
It maybe that the netcdf-cxx4 version and corresponding netcdf-c version are too old. The latest netcdf-cxx4 is v4.3.1. In theory we could set a minimum version of netcdf-cxx4 for CMake to find but the packaged netcdf-cxx4 cmtarget doesn't appear to contain that information... yet.
